version: '3.1'


services:
  mediumserver:
    image: melzchelli/stigld-mediumserver
    ports:
      - "8080:8080"
    depends_on: 
        - fusekiserver

  visualise:
    image: melzchelli/stigld-visualise:v3
    ports:
      - "4200:4200"
    depends_on:
      - mediumserver

  fusekiserver:
    image: melzchelli/stigld-fusekiserver
    ports:
      - "3230:3230"
      
  agentrunner:
    image: melzchelli/stigld-agentrunner
    depends_on: 
       - mediumserver
       - visualise
